# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb6bbc6616be9f25197f7fa744e7f494c679a639f4a6d6df3c5e98978ff74ce0f2ed604ab6e68aedca808bce136cef1742a475933f2f62538a17198c76dfa3c

test:
  secret_key_base: 8f8456d31ec565a77fb27084a4b3731852773da304e8e561becfb72eb57dc625d67d062770f510ddbd369f9603540634f7b6a3a2fdcdf99953e2f4cb6e67ef97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
